# Generated by Django 6.1.1 on 2026-09-17 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(choices=[('service', 'Услуга'), ('order', 'Заказ')], default='service', max_length=10, verbose_name='Тип публикации')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('in_progress', 'В работе'), ('closed', 'Закрыта'), ('archived', 'Архивирована')], default='active', max_length=15, verbose_name='Статус')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('price_type', models.CharField(choices=[('fixed', 'Фиксированная'), ('hourly', 'Почасовая'), ('negotiable', 'Договорная')], default='fixed', max_length=10, verbose_name='Тип цены')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='Изображение')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='publications', to='core.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['publication_type', 'status'], name='core_public_publica_265b23_idx'), models.Index(fields=['-created_at'], name='core_public_created_6c64c2_idx')],
            },
        ),
    ]
